#docker-compose -f 1-sql-server.yml up --detach
services:
  sql-server-db:
    container_name: sql-server
    hostname: sql-server
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    expose: 
    - 1443
    environment:
      SA_PASSWORD: "welcome1"
      ACCEPT_EULA: "Y"
    volumes: 
      - type: bind
        source: .
        target: /app
        read_only: true