#localhost:3306-root-testedb-root
version: '3'

services:
  mysql:
    image: mysql
    container_name: "mysql"
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    #    volumes:
    #      - ../../data/mysql:/var/lib/postgresql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
    ports:
      - 3306:3306

#docker-compose -f mysql.yml up