#localhost:3306-root-testedb-root
version: '3'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    container_name: "mongodb"
    hostname: mongodb
    #   volumes:
    #     - ../../data/mongodb:/data/db
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=database
      - MONGODB_APPLICATION_USER=root
      - MONGODB_APPLICATION_PASS=pass
    ports:
      - 27017:27017

#docker-compose up